complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 3
  ComplexInterface:
    active: true
    threshold: 14
    includeStaticDeclarations: false
    includePrivateDeclarations: false
  LongParameterList:
    functionThreshold: 4
    constructorThreshold: 7
    ignoreDefaultParameters: true
    ignoreDataClasses: true
  LabeledExpression:
    active: false
  LargeClass:
    active: true
    threshold: 200
  LongMethod:
    active: true
    threshold: 30
  MethodOverloading:
    active: true
    threshold: 2
  NestedBlockDepth:
    active: true
    threshold: 4
  TooManyFunctions:
    thresholdInFiles: 16
    thresholdInClasses: 16
    thresholdInInterfaces: 16
    thresholdInObjects: 16
    thresholdInEnums: 16
    ignorePrivate: false
    ignoreOverridden: true
    ignoreDeprecated: true
  StringLiteralDuplication:
    active: true
    threshold: 2
    ignoreAnnotation: true
    excludeStringsWithLessThan5Characters: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: '^(_|(ignore|expected).*)'
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: false
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: false
  ExceptionRaisedInUnexpectedLocation:
    active: true
    methodNames: [toString, hashCode, equals, finalize]
  InstanceOfCheckForException:
    active: true
  NotImplementedDeclaration:
    active: true
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
  SwallowedException:
    active: true
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true

naming:
  active: true
  EnumNaming:
    active: true
    enumEntryPattern: '^[A-Z][_A-Z]*'
  ForbiddenClassName:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt']
    forbiddenName: ['Context']
  FunctionMinLength:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt']
    minimumFunctionNameLength: 3
  InvalidPackageDeclaration:
    active: true
    rootPackage: 'com.mazaj.seller'
  VariableMinLength:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt']
    minimumVariableNameLength: 3
  TopLevelPropertyNaming:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/*.Test.kt', '**/*.Spec.kt', '**/*.Spek.kt']
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[a-z][A-Za-z0-9]*'
    privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'

formatting:
  active: true
  android: true
  autoCorrect: true
  AnnotationOnSeparateLine:
    active: true
    autoCorrect: true
  EnumEntryNameCase:
    active: true
    autoCorrect: true
  ImportOrdering:
    active: true
    autoCorrect: true
  MaximumLineLength:
    maxLineLength: 160
  NoEmptyFirstLineInMethodBlock:
    active: true
    autoCorrect: true
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4
    continuationIndentSize: 4
  NoWildcardImports:
    active: false

style:
  ForbiddenComment:
    active: false
  MaxLineLength:
    maxLineLength: 160
  UnusedPrivateMember:
    active: true
  ForbiddenMethodCall:
    active: true
  WildcardImport:
    active: false
  CollapsibleIfStatements:
    active: true
  DataClassContainsFunctions:
    active: true
  DataClassShouldBeImmutable:
    active: false
  EqualsNullCall:
    active: true
  EqualsOnSignatureLine:
    active: true
  ExplicitCollectionElementAccessMethod:
    active: true
  ExplicitItLambdaParameter:
    active: true
  ExpressionBodySyntax:
    active: true
  FunctionOnlyReturningConstant:
    active: true
  MandatoryBracesIfStatements:
    active: true
  MayBeConst:
    active: true
  NoTabs:
    active: true
  OptionalUnit:
    active: true
  OptionalWhenBraces:
    active: true
  PreferToOverPairSyntax:
    active: true
  RedundantExplicitType:
    active: true
  RedundantVisibilityModifierRule:
    active: true
  SerialVersionUIDInSerializableClass:
    active: true
  SpacingBetweenPackageAndImports:
    active: true
  TrailingWhitespace:
    active: true
  UnderscoresInNumericLiterals:
    active: true
  UnnecessaryAnnotationUseSiteTarget:
    active: true
  UnnecessaryApply:
    active: true
  UnnecessaryLet:
    active: true
  UnnecessaryParentheses:
    active: true
  UntilInsteadOfRangeTo:
    active: true
  UnusedImports:
    active: true
  UseDataClass:
    active: true
  UseIfInsteadOfWhen:
    active: true
  UseRequire:
    active: true
  VarCouldBeVal:
    active: true

potential-bugs:
  active: true
  Deprecation:
    active: true
  HasPlatformType:
    active: true
  ImplicitDefaultLocale:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  UnconditionalJumpStatementInLoop:
    active: true
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCode:
    active: true
  UnsafeCast:
    active: true
  UselessPostfixExpression:
    active: true
